Repository trinodb/charts, pull requests merged in 2022-03, with the labels that each got.

#29 Add support for configuring exchange manager properties
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/values.yaml
Labels: cla-signed, release-note

#25 Add support for init containers for worker and coordinator
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
Labels: cla-signed, release-note

#24 Add Kubernetes service accounts to the chart
  charts/trino/README.md
  charts/trino/templates/_helpers.tpl
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/serviceaccount.yaml
  charts/trino/values.yaml
Labels: cla-signed, release-note

#30 Fix exchange-manager.properties and bump version
  README.md
  charts/trino/Chart.yaml
  charts/trino/templates/configmap-worker.yaml
Labels: cla-signed, release-note-none

#34 Add support for configuring PASSWORD authentication
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/secret.yaml
  charts/trino/values.yaml
Labels: cla-signed, release-note

#26 Provide different JVM configs for co-ordinator and workers
  charts/trino/README.md
  charts/trino/ci/custom-values.yaml
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values-coordinator.yaml
  charts/trino/values-worker.yaml
  charts/trino/values.yaml
Labels: cla-signed, release-note

#17 feat: customizable imagePullSecrets
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
Labels: cla-signed
