Repository trinodb/charts, pull requests merged in 2024-11, with the labels that each got.

#251 Release both trino and trino-gateway charts
  .github/workflows/ci-cd.yaml
Labels: cla-signed

#256 Support setting annotations in deployments
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
  test-values.yaml
Labels: enhancement, cla-signed

#231 add_separate_group.db_secret
  charts/trino/README.md
  charts/trino/templates/_helpers.tpl
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/secret.yaml
  charts/trino/values.yaml
Labels: enhancement, cla-signed

#252 Add support for Database resource group manager
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/tests/test-connection.yaml
  charts/trino/values.yaml
  test-resource-groups-properties-values.yaml
  test-values.yaml
  test.sh
Labels: enhancement, cla-signed

#262 Prepare next release
  README.md
  charts/trino/Chart.yaml
  charts/trino/README.md
Labels: ignore-for-release
