Repository trinodb/charts, pull requests merged in 2024-12, with the labels that each got.

#268 Improve readme content
  README.md
Labels: cla-signed

#270 Release Trino Gateway chart 1.13.0
  charts/gateway/Chart.yaml
  charts/gateway/README.md
Labels: cla-signed

#272 Improve overview docs
  README.md
Labels: cla-signed, ignore-for-release

#266 Add service monitor API version override
  charts/trino/README.md
  charts/trino/templates/servicemonitor-coordinator.yaml
  charts/trino/templates/servicemonitor-worker.yaml
  charts/trino/values.yaml
Labels: enhancement, cla-signed

#258 Add service annotations support to Trino Gateway Chart
  charts/gateway/README.md
  charts/gateway/templates/service.yaml
  charts/gateway/values.yaml
Labels: enhancement, cla-signed

#260 Add envFrom and remove lookup
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/secrets.yaml
  charts/gateway/values.yaml
  tests/gateway/test-values-with-env.yaml
  tests/gateway/test.sh
Labels: enhancement, cla-signed, breaking-change

#276 Fixed typo in Trino JMX documentation
  charts/trino/README.md
  charts/trino/values.yaml
  tests/trino/test-values.yaml
Labels: documentation, cla-signed
