Repository trinodb/charts, pull requests merged in 2024-09, with the labels that each got.

#190 mv roles configmap to another file
  charts/trino/templates/configmap-access-control.yaml
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/deployment-coordinator.yaml
Labels: enhancement, cla-signed

#218 Support custom password auth properties file
  charts/trino/templates/configmap-coordinator.yaml
Labels: enhancement, cla-signed

#207 Allow to set resources for the JMX Exporter container
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/values.yaml
Labels: enhancement, cla-signed

#220 Automatically restart the worker when the catalog changes
  charts/trino/templates/deployment-worker.yaml
Labels: cla-signed

#216 Make exchange manager conditional
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/values.yaml
  test-exchange-manager-values.yaml
  test.sh
Labels: cla-signed, breaking-changes

#222 Fix JMX Exporter container port spec
  charts/trino/README.md
  charts/trino/templates/configmap-jmx-exporter.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/values.yaml
Labels: bug, cla-signed

#223 Update Trino and chart version
  README.md
  charts/trino/Chart.yaml
  charts/trino/README.md
Labels: cla-signed

#228 Optional catalogs and related configmap
  charts/trino/README.md
  charts/trino/templates/configmap-catalog.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
Labels: cla-signed

#232 Update Trino and the chart version
  README.md
  charts/trino/Chart.yaml
  charts/trino/README.md
Labels: cla-signed
