Repository trinodb/charts, pull requests merged in 2024-10, with the labels that each got.

#234 Test with latest Helm
  .github/workflows/ci-cd.yaml
Labels: cla-signed

#233 remove `.Values.server.config.http` section from chart
  charts/trino/README.md
  charts/trino/values.yaml
Labels: cla-signed

#238 Remove invalid default from `imagePullSecrets`
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
Labels: bug, cla-signed

#227 Add option to enable JMX exporter on workers
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-jmx-exporter.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/service-coordinator.yaml
  charts/trino/templates/service-worker.yaml
  charts/trino/templates/servicemonitor-coordinator.yaml
  charts/trino/templates/servicemonitor-worker.yaml
  charts/trino/templates/tests/test-jmx.yaml
  charts/trino/values.yaml
  test-values.yaml
  test.sh
Labels: cla-signed

#226 Add option to enable worker graceful shutdown
  charts/trino/README.md
  charts/trino/templates/configmap-access-control-coordinator.yaml
  charts/trino/templates/configmap-access-control-worker.yaml
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/tests/test-graceful-shutdown.yaml
  charts/trino/values.yaml
  test-graceful-shutdown-values.yaml
  test.sh
Labels: enhancement, cla-signed

#239 Allow autoscaling by memory utilization
  charts/trino/README.md
  charts/trino/templates/autoscaler.yaml
  charts/trino/values.yaml
  test-values.yaml
Labels: enhancement, cla-signed

#243 Add `networkpolicy` support
  .github/workflows/ci-cd.yaml
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/networkpolicy.yaml
  charts/trino/templates/tests/test-networkpolicy.yaml
  charts/trino/values.yaml
  test-values.yaml
Labels: cla-signed

#244 Add deployment spec properties to coordinator and worker
  charts/trino/README.md
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/values.yaml
  test-values.yaml
Labels: cla-signed

#241 Allow setting nodePort in .Values.coordinator.additionalExposedPorts
  charts/trino/README.md
  charts/trino/templates/service-coordinator.yaml
  charts/trino/values.yaml
  test-values.yaml
Labels: enhancement, cla-signed

#247 Use PR labels when generating release notes
  .github/release.yml
Labels: cla-signed
