Repository trinodb/charts, pull requests merged in 2025-03, with the labels that each got.

#320 Enable templating of environment name
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/values.yaml
  tests/trino/test-values.yaml
Labels: enhancement, cla-signed

#321 Include namespace in port-forward command
  charts/trino/templates/NOTES.txt
Labels: bug, cla-signed

#319 Updated Trino app version to 474
  README.md
  charts/trino/Chart.yaml
  charts/trino/README.md
Labels: cla-signed, ignore-for-release

#323 Fix secret naming consistency
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/secrets.yaml
Labels: enhancement, cla-signed
