Repository trinodb/charts, pull requests merged in 2025-05, with the labels that each got.

#343 Refactor Trino Gateway test-connection
  charts/gateway/templates/tests/test-connection.yaml
Labels: cla-signed, ignore-for-release

#339 Add Pod Disruption Budget configuration to Trino Gateway
  charts/gateway/README.md
  charts/gateway/templates/poddisruptionbudget.yaml
  charts/gateway/values.yaml
Labels: cla-signed

#340 Add checksum annotation for Trino Gateway configuration to trigger ro…
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: cla-signed

#342 Add lifecycle configuration support to Trino Gateway
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: enhancement, cla-signed

#347 Add terminationGracePeriodSeconds to Trino Gateway Deployment
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: enhancement, cla-signed

#335 initContainers for gateway
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
  tests/gateway/test-values.yaml
Labels: enhancement, cla-signed

#350 Fix rendering notes for load-balancer service
  charts/gateway/templates/NOTES.txt
Labels: cla-signed

#334 volumes and volumeMounts as lists with tpl
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: bug, cla-signed

#338 Add annotations documentation for coordinator and worker Trino Pods
  charts/trino/README.md
  charts/trino/values.yaml
Labels: documentation, cla-signed

#344 Enhance graceful shutdown handling in worker deployment
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/tests/test-graceful-shutdown.yaml
  tests/trino/test-graceful-shutdown-values.yaml
Labels: bug, cla-signed

#312 Remove extra spaces in comments
  charts/trino/README.md
  charts/trino/values.yaml
Labels: documentation, cla-signed

#336 Add configurable topologySpreadConstraints for Trino gateway deployment
  charts/gateway/README.md
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: enhancement, cla-signed

#351 Run CI tests only if Trino and Gateway file change
  .github/workflows/ci-cd.yaml
Labels: cla-signed, ignore-for-release
