Repository trinodb/charts, pull requests merged in 2025-02, with the labels that each got.

#286 Template external secrets configs injection
  charts/trino/templates/deployment-coordinator.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/ingress.yaml
  charts/trino/templates/tests/test-connection.yaml
  tests/trino/test-values.yaml
  tests/trino/test.sh
Labels: enhancement, cla-signed

#277 Adding worker autoscaling support with KEDA
  charts/trino/README.md
  charts/trino/templates/configmap-coordinator.yaml
  charts/trino/templates/configmap-worker.yaml
  charts/trino/templates/deployment-worker.yaml
  charts/trino/templates/keda-scaledobject.yaml
  charts/trino/templates/tests/test-connection.yaml
  charts/trino/values.yaml
  tests/trino/test-values.yaml
  tests/trino/test.sh
Labels: enhancement, cla-signed, breaking-change

#301 Prepare for next release of the Trino chart
  README.md
  charts/trino/Chart.yaml
  charts/trino/README.md
Labels: cla-signed, ignore-for-release

#296 Remove deprecated settings from gateway config
  charts/gateway/README.md
  charts/gateway/values.yaml
  tests/gateway/test-values-with-env.yaml
  tests/gateway/test-values.yaml
Labels: cla-signed

#304 Use health endpoints of Trino Gateway
  charts/gateway/templates/deployment.yaml
Labels: cla-signed

#289 Release Trino Gateway chart 1.14.0
  README.md
  charts/gateway/Chart.yaml
  charts/gateway/README.md
Labels: cla-signed, ignore-for-release

#305 Remove DB initialization from tests
  charts/gateway/templates/tests/test-connection.yaml
Labels: cla-signed, ignore-for-release
